[package]
name = "simulation-runner"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
simulation-core = { path = "../simulation-core" }
simulation-model = { path = "../simulation-model" }
simulation-save = { path = "../simulation-save" }

[lints]
workspace = true
