[package]
name = "simulation-save"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
simulation-model = { path = "../simulation-model" }

[dev-dependencies]
simulation-worldgen = { path = "../simulation-worldgen" }

[lints]
workspace = true
